# Generated by Django 3.0.8 on 2020-07-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergameinfo',
            name='owner',
        ),
    ]
