# Generated by Django 3.0.8 on 2020-07-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_playergameinfo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='is_owner',
            field=models.BooleanField(null=True),
        ),
    ]
