# Generated by Django 3.0.8 on 2020-07-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_playergameinfo_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
