# Generated by Django 3.0.8 on 2020-07-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_trials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='trials',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
