# Generated by Django 3.0.8 on 2020-07-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200709_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='trials',
            field=models.IntegerField(default=0),
        ),
    ]
